config/routes.rb
Rails.application.routes.draw do
  get 'card/new'

  get 'card/show'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'hp_top#index' # ログインor新規登録を選ぶページ
  resources :hp_top, only: :new  # 新規登録方法を選ぶページ
  resources :about, only: :index
  resources :koukoku, only: :index, path: '/about/koukoku/'
  resources :projects, only: :index
  resources :contact, only: :index
  resources :donation, only: :index
  resources :mypage, only: :index
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true, uniqueness: true

  has_many :sns_credentials
  has_many :card
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # response.headers['X-Frame-Options'] = 'ALLOWALL'

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :firstname, :lastname])
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/donation_controller.rb
class DonationController < ApplicationController
end

app/controllers/hp_top_controller.rb
class HpTopController < ApplicationController
  def index
  end
end

app/controllers/koukoku_controller.rb
class KoukokuController < ApplicationController
  def index
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/hp_top_helper.rb
module HpTopHelper
end

app/helpers/koukoku_helper.rb
module KoukokuHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/card/new.html.haml
= render "hp_top/header"
.body
  .sinki
    = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %label カード番号
      = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %ul.signup-card-list
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266",width:"49px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266",width:"34px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?238737266",width:"30px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266",width:"32px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266",width:"21px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266",width:"32px",height:"20px"
        %li
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266",width:"32px",height:"20px"
      %br
      %label 有効期限
      %select#exp_month{name: "exp_month", type: "text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      %span 月/
      %select#exp_year{name: "exp_year", type: "text"}
        %option{value: ""} --
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
        %option{value: "2030"}30
      %span 年
      %br
      %label セキュリティコード
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      #card_token
      = submit_tag "追加する", id: "token_submit"
= render "hp_top/footer.haml"

app/views/card/show.html.haml
-# %h1 Card#show
-# %p Find me in app/views/card/show.html.haml
.form-content
  %label 登録クレジットカード情報
  %br
  = "**** **** **** " + @default_card_information.last4
  %br
  - exp_month = @default_card_information.exp_month.to_s
  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
  = exp_month + " / " + exp_year
  = form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
    %input{ type: "hidden", name: "card_id", value: "" }
    %button 削除する