config/routes.rb
Rails.application.routes.draw do
  get 'card/new'

  get 'card/show'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'hp_top#index' # ログインor新規登録を選ぶページ
  resources :hp_top, only: :new  # 新規登録方法を選ぶページ
  resources :about, only: :index
  resources :koukoku, only: :index, path: '/about/koukoku/'
  resources :projects, only: :index
  resources :contact, only: :index
  resources :donation, only: :index
  resources :mypage, only: :index
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true, uniqueness: true

  has_many :sns_credentials
  has_many :card
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # response.headers['X-Frame-Options'] = 'ALLOWALL'

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :firstname, :lastname])
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/donation_controller.rb
class DonationController < ApplicationController
end

app/controllers/hp_top_controller.rb
class HpTopController < ApplicationController
  def index
  end
end

app/controllers/koukoku_controller.rb
class KoukokuController < ApplicationController
  def index
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/hp_top_helper.rb
module HpTopHelper
end

app/helpers/koukoku_helper.rb
module KoukokuHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.haml
.wrapper
  = render "hp_top/header.haml"
  .body
    .about 
      %h2 一般社団法人アラヤシキについて 
      %br 目的
      %br 当法人は、芸術・文化の振興、普及及び発展に寄与すること、並びに地 域の振興を目的とし、その目的に資するために、次の事業を行う。
      %br (1) 文化及び芸術の振興を目的とする事業
      %br (2) 文化及び芸術の活動(事業)を行う個人(団体)への支援を目的とする 事業
      %br (3) 文化及び芸術に関連する施設の管理運営を目的とする事業
      %br (4) 地域の振興を目的とする事業
      %br (5) 地域の活動(事業)を行う個人(団体)への支援を目的とする事業
      %br (6) 地域の振興に関連する施設の管理運営を目的とする事業
      %br (7) 前各号に附帯又は関連する一切の事業
      %br 
      設立時理事  小手川 望
      %br 
      設立時理事  森本 洋史
      %br 設立時代表理事  寺川 大地
      %br
      = link_to koukoku_index_path do
        定款
      公開情報 2020年7月21日現在 
  = render "hp_top/footer.haml"

app/views/contact/index.html.haml
.wrapper
  = render "hp_top/header.haml"
  .body
    .contact
      %h2.contact-title お問い合わせ
      %br/
      %br/
      %br/
      %p.contact-text
        ●お電話でのお問い合わせ
        %br/
        受付時間：13:00〜19:00
        %br/
        電話番号：
        %br/
        %br/
        %br/
        ●所在地
        %br/
        〒557-0002 大阪府大阪市西成区太子１丁目３−２６
        %br/
        %br/
      
      %iframe.contact__map{src: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3282.2433092732326!2d135.50211271516176!3d34.648557780447895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000dd8af6b0af5b%3A0x628085f258385071!2z44CSNTU3LTAwMDIg5aSn6Ziq5bqc5aSn6Ziq5biC6KW_5oiQ5Yy65aSq5a2Q77yR5LiB55uu77yT4oiS77yS77yW!5e0!3m2!1sja!2sjp!4v1594787560586!5m2!1sja!2sjp", style: "border:0;", tabindex: "0",allowfullscreen: "", aria: {hidden: :true}, frameborder: "0", height: "400", width: "1160" }

  = render "hp_top/footer.haml"

app/views/donation/index.html.haml
.wrapper
  = render "hp_top/header.haml"
  寄付について
  %br/
  ログイン後、寄付フォーム
  

  = render "hp_top/footer.haml"

app/views/hp_top/_footer.haml
.footer
  .small 一般社団法人アラヤシキ all rights reserved

-# = link_to '#',alt: 'admin',class: 'neko'do
-#   %i.fas.fa-cat 
-#     .adm adm
    
          

app/views/hp_top/_header.haml
.header
  .h1__title 
    = link_to root_path do
      = image_tag 'top1.png', class: 'top-logo' 
      一般社団法人アラヤシキ

  
  %ul.header-links
    %li.header-link
      = link_to 'About','/about'
        
    %li.header-link
      = link_to 'projects','/projects'
        
    -# %li.header-link
    -#   = link_to 'note','#' 
        
    %li.header-link
      = link_to 'contact','/contact' 
    %li.header-link
      = link_to 'donation','/donation' 
        
  .mypage
    - if user_signed_in?
      = link_to 'log out', destroy_user_session_path , method: :delete , alt: 'signin',class: 'sign' 
      = link_to "#{current_user .nickname}",'/mypage',class: 'nickname'
    - else
      = link_to 'sign up', new_user_registration_path,class: 'sign'
      = link_to 'log in', new_user_session_path ,class: 'sign'

-# = link_to 'admin','#',alt: 'admin',class: 'adm' 

app/views/hp_top/_main.haml
.body
  .main 
    .main_news
      %h2 お知らせ
      .main_news_top
        %table
          %tbody
            %tr
              %td.time 2020/11/21.22.23
              %td.text 
                [イベント] 
                %a{href:"#",} ドラゴン映画祭
                協力(予定)
            %tr
              %td.time 2020/00/00
              %td.text [テキスト] テキスト
            %tr
              %td.time 2020/07/30-31
              %td.text  
                [イベント] 
                %a{href:"https://www.facebook.com/events/1138912663159351"} あらやしき 1971
                ＠earth 主催
            %tr
              %td.time 2020/09/07
              %td.text  [お知らせ] 一般社団法人アラヤシキ 設立
            %tr
              %td.time 2020/09/07
              %td.text  一般社団法人アラヤシキ 設立
      %ul.top_pic
        %li
        = image_tag 'IMG_5919.JPG', alt:'top1', class:'top-image'
        %li
        = image_tag 'IMG_8243.JPG', alt:'top2', class:'top-image'
        %li
        = image_tag 'IMG_0075.JPG', alt:'top2', class:'top-image'

app/views/hp_top/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "footer"

app/views/koukoku/index.html.haml
.wrapper
  = render "hp_top/header.haml"
  .koukoku
    = link_to ' 定款', 'https://www.dropbox.com/s/7vviwrqyc7ur9h3/20200721%E3%82%A2%E3%83%A9%E3%83%A4%E3%82%B7%E3%82%AD%E9%9B%BB%E5%AD%90%E5%AE%9A%E6%AC%BE%E7%A2%BA%E8%AA%8D%E7%94%A8.pdf?dl=0'
    ファイルへのリンク
  = render "hp_top/footer.haml"
-# = link_to 'Google Search', 'https://www.google.co.jp'
-# %a{href:"https://www.dropbox.com/s/7vviwrqyc7ur9h3/20200721%E3%82%A2%E3%83%A9%E3%83%A4%E3%82%B7%E3%82%AD%E9%9B%BB%E5%AD%90%E5%AE%9A%E6%AC%BE%E7%A2%BA%E8%AA%8D%E7%94%A8.pdf?dl=0"} 定款

app/views/mypage/index.html.haml
= render "hp_top/header"
.body
  .sinki
    = link_to 'クレジット入力','/card/new' 
  = render "hp_top/footer.haml"

app/views/projects/index.html.haml
.wrapper
  = render "hp_top/header.haml"
  .body
    .main 
      .main_news
        経歴(仮)
        .youtube-container
          %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/Oe-rTLE7dOw", :width => "560"}
        
      -# %iframe{:allow => "encrypted-media", :allowtransparency => "true", :frameborder => "0", :height => "500", :scrolling => "no", :src => "https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fevents%2F1138912663159351&tabs=timeline&width=0&height=0&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false&appId=615522389361210", :style => "border:none;overflow:hidden", :width => "500"}



  = render "hp_top/footer.haml"